#!/usr/bin/env bash

# shellcheck disable=2155
post_name=$1
# Add a single md ending.
post_name=${post_name%%.*}.md
root_path=$(git rev-parse --show-toplevel)
if [[ $PWD == "$root_path" ]]; then
    hugo new "content/posts/$(date -u +%Y-%m-%d)-$post_name"
else
    post_path=$(realpath "$PWD/$post_name" --relative-to="$root_path")
    cd "$root_path" || exit
    hugo new "$post_path"
fi
