#!/usr/bin/env bash

# Usage:
# $ post hello world
# $ Content "hello-world.md" created

post_name=$*
post_name=$(echo "$post_name" | tr ' ' '-') # Replace spaces
post_name=$(echo "$post_name" | tr '[:upper:]' '[:lower:]') # Make lowercase
# Add a single md ending.
post_name=${post_name%%.*}.md
root_path=$(git rev-parse --show-toplevel)
if [[ $PWD == "$root_path" ]]; then
    hugo new "content/posts/$(date -u +%Y-%m-%d)-$post_name"
else
    post_path=$(realpath "$PWD/$post_name" --relative-to="$root_path")
    cd "$root_path" || exit
    hugo new "$post_path"
fi
